[[solver]]
name = "FractalSolver"                                 # Arbitrary name given to this solver, must be unique
endpoint = "http://0.0.0.0:6000"                       # 
absolute-slippage = "40000000000000000"                # Denominated in wei, optional
relative-slippage = "0.1"                              # Percentage in the [0, 1] range
account = "0xDF4296e752FD08b2d7Db4101B98a48b74E59FD56" # public key of an actual solver

[submission]
gas-price-cap = "1000000000000" # 1000 Gwei

[[submission.mempool]]
mempool = "public"
revert-protection = true

[contracts] # Optionally override the contract addresses, necessary on less popular blockchains
gp-v2-settlement = "0x9008D19f58AAbD9eD0D60971565AA8510560ab41"
weth = "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"

[liquidity]
