[[solver]]
name = "FractalSolver"                                 # Arbitrary name given to this solver, must be unique
endpoint = "http://0.0.0.0:6000"                       # 
absolute-slippage = "40000000000000000"                # Denominated in wei, optional
relative-slippage = "0.1"                              # Percentage in the [0, 1] range
account = "0xDF4296e752FD08b2d7Db4101B98a48b74E59FD56" # public key of an actual solver

[submission]
gas-price-cap = "1000000000000" # 1000 Gwei

[[submission.mempool]]
mempool = "public"
revert-protection = true

[contracts] # Optionally override the contract addresses, necessary on less popular blockchains
gp-v2-settlement = "0x9008D19f58AAbD9eD0D60971565AA8510560ab41"
weth = "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"

[liquidity]
base-tokens = [
    "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2",
    "0x6B175474E89094C44Da98b954EedeAC495271d0F",
    "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
    "0xdAC17F958D2ee523a2206206994597C13D831ec7",
    "0xc00e94Cb662C3520282E6f5717214004A7f26888",
    "0x9f8F72aA9304c8B593d555F12eF6589cC3A579A2",
    "0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599",
    "0x6810e776880C02933D47DB1b9fc05908e5386b96",
]
graph-api-base-url = "https://api.thegraph.com/subgraphs/name/"

[[liquidity.uniswap-v2]] # Uniswap V2 configuration
preset = "uniswap-v2" # or "sushi-swap", "honeyswap", "baoswap", "pancake-swap", etc.

[[liquidity.uniswap-v2]] # Uniswap V2 configuration
preset = "pancake-swap"

[[liquidity.balancer-v2]] # Balancer V2 configuration
preset = "balancer-v2"
pool-deny-list = []    # optional

[[liquidity.uniswap-v3]] # Uniswap V3 configuration
preset = "uniswap-v3"
# max_pools_to_initialize = 100 # doesn't work, hardcode default_max_pools_to_initialize instead
